# Worshop 2.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [1]:
import numpy as np
print(np.__version__)

1.26.4


2) Создать нулевой вектор размера 10

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7

In [3]:
np.full(7, 7)

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [4]:
np.arange(10, 100, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [5]:
tmp = np.random.random_sample(4)
print (tmp)
np.flip(tmp)

[0.9793159  0.44997376 0.08184689 0.73802885]


array([0.73802885, 0.08184689, 0.44997376, 0.9793159 ])

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [6]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [7]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [8]:
tmp = np.diag([1, 2, 3, 4])
tmp[tmp == 0] = 7
tmp

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [10]:
(np.arange(25)%5).reshape(5,5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]], dtype=int32)

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [11]:
tmp = np.random.random_sample((10,10))
print(tmp)
tmp - tmp.mean(axis = 1, keepdims=True)

[[6.22039880e-01 2.28609828e-01 5.17476017e-01 3.89949395e-01
  1.16460811e-01 1.45997384e-01 6.54956074e-01 1.87263960e-01
  8.29425764e-01 3.63722567e-01]
 [5.32628183e-01 3.62995343e-01 9.96790514e-01 8.82286788e-02
  9.18355299e-01 3.05078004e-01 1.44630203e-01 8.45223400e-01
  1.85604290e-01 9.99577446e-01]
 [4.15340895e-01 1.54499273e-02 6.48504501e-01 8.35612718e-01
  9.75457566e-01 1.91676311e-01 2.02041903e-01 8.00349207e-01
  3.23708822e-01 9.53809473e-02]
 [7.26507792e-01 4.33074209e-01 7.39301485e-01 7.78167795e-02
  6.47969291e-01 4.29899278e-01 6.28023583e-01 8.14008248e-01
  5.04350029e-01 5.14604655e-01]
 [7.62745096e-01 9.78889472e-01 9.52133491e-01 8.38046989e-01
  8.79614532e-01 7.09433151e-01 3.86643053e-01 5.35217670e-01
  3.38672859e-01 6.04827614e-01]
 [7.04080416e-01 5.65664485e-01 6.88357916e-01 1.94579868e-01
  4.51693002e-01 6.50505603e-01 3.13363499e-01 9.57684471e-01
  9.44729570e-01 7.17769590e-01]
 [6.17131352e-01 5.49186682e-01 4.01715085e-01 9.82603070e

array([[ 0.21644971, -0.17698034,  0.11188585, -0.01564077, -0.28912936,
        -0.25959278,  0.24936591, -0.21832621,  0.4238356 , -0.0418676 ],
       [-0.00528295, -0.17491579,  0.45887938, -0.44968246,  0.38044416,
        -0.23283313, -0.39328093,  0.30731226, -0.35230685,  0.46166631],
       [-0.03501139, -0.43490235,  0.19815222,  0.38526044,  0.52510529,
        -0.25867597, -0.24831038,  0.34999693, -0.12664346, -0.35497133],
       [ 0.17495226, -0.11848133,  0.18774595, -0.47373876,  0.09641376,
        -0.12165626,  0.07646805,  0.26245271, -0.04720551, -0.03695088],
       [ 0.0641227 ,  0.28026708,  0.2535111 ,  0.1394246 ,  0.18099214,
         0.01081076, -0.31197934, -0.16340472, -0.35994953, -0.09379478],
       [ 0.08523757, -0.05317836,  0.06951507, -0.42426297, -0.16714984,
         0.03166276, -0.30547934,  0.33884163,  0.32588673,  0.09892675],
       [ 0.12023184,  0.05228717, -0.09518443,  0.48570355, -0.47961765,
        -0.49611394,  0.3299414 ,  0.05411969

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [12]:
tmp = np.random.random_sample((10,10))
print(tmp)
tmp - np.median(tmp, axis = 0, keepdims=True)

[[0.56756472 0.34040342 0.70905626 0.32220152 0.6367141  0.7831633
  0.42493344 0.68126484 0.09451267 0.60519286]
 [0.52777784 0.81480456 0.8978894  0.82679355 0.57242363 0.40686082
  0.27592377 0.53691385 0.52192513 0.79256846]
 [0.57806751 0.13420686 0.47140249 0.59445377 0.33994441 0.21559031
  0.78250912 0.46307609 0.39391954 0.64545744]
 [0.99531267 0.93616423 0.37084152 0.30224565 0.72665042 0.61955532
  0.01585228 0.93134977 0.49499099 0.79417563]
 [0.15258395 0.71894225 0.93239707 0.70314934 0.8991647  0.37299095
  0.75027489 0.12330225 0.59839508 0.3925171 ]
 [0.57433116 0.0793182  0.45860444 0.33349528 0.89307992 0.28445996
  0.42609172 0.36889461 0.46332252 0.96405445]
 [0.75816662 0.05364912 0.58267646 0.74399134 0.11506891 0.4481781
  0.97606205 0.33901962 0.34313344 0.61528568]
 [0.62414248 0.97716053 0.53608121 0.06036612 0.34284235 0.62496845
  0.82387493 0.24330993 0.84664514 0.21045467]
 [0.83416191 0.56502281 0.05451802 0.07083496 0.71204659 0.13808944
  0.92799179 0

array([[-0.03354027, -0.30157911,  0.14967742, -0.00564688, -0.03766624,
         0.39323741, -0.34145857,  0.26527949, -0.34200294, -0.0251787 ],
       [-0.07332716,  0.17282203,  0.33851056,  0.49894515, -0.10195671,
         0.01693493, -0.49046823,  0.1209285 ,  0.08540952,  0.1621969 ],
       [-0.02303748, -0.50777567, -0.08797634,  0.26660536, -0.33443593,
        -0.17433557,  0.01611711,  0.04709074, -0.04259607,  0.01508588],
       [ 0.39420767,  0.2941817 , -0.18853732, -0.02560275,  0.05227008,
         0.22962944, -0.75053972,  0.51536442,  0.05847538,  0.16380407],
       [-0.44852104,  0.07695972,  0.37301823,  0.37530093,  0.22478436,
        -0.01693493, -0.01611711, -0.2926831 ,  0.16187947, -0.23785446],
       [-0.02677384, -0.56266433, -0.1007744 ,  0.00564688,  0.21869958,
        -0.10546592, -0.34030029, -0.04709074,  0.02680691,  0.33368289],
       [ 0.15706162, -0.58833342,  0.02329763,  0.41614293, -0.55931143,
         0.05825221,  0.20967004, -0.07696573

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [13]:
tmp = np.random.random_sample((5,5))
max = tmp.max(axis =1,keepdims=True)
min = tmp.min(axis =1,keepdims=True)
np.concatenate((tmp, max, min),axis = 1)

array([[0.40274841, 0.3176533 , 0.52203783, 0.61067328, 0.67707883,
        0.67707883, 0.3176533 ],
       [0.45051887, 0.64399707, 0.46928702, 0.79968825, 0.44832136,
        0.79968825, 0.44832136],
       [0.7904098 , 0.52203168, 0.00386814, 0.36033809, 0.94300945,
        0.94300945, 0.00386814],
       [0.13870623, 0.23900678, 0.73486443, 0.17336561, 0.40646635,
        0.73486443, 0.13870623],
       [0.58560801, 0.69081396, 0.9264431 , 0.29574725, 0.04756023,
        0.9264431 , 0.04756023]])

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [14]:
tmp1 =np.mat(np.arange(0,51)[1::2]).reshape(5,5)
print(tmp1)
tmp2 =np.mat(np.arange(0,51)[2::2]).reshape(5,5)
print(tmp2)
tmp3 = tmp1@tmp2
print(tmp3)
np.linalg.inv(tmp3) # обратной матрицы не существует

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]
[[ 750  800  850  900  950]
 [1850 2000 2150 2300 2450]
 [2950 3200 3450 3700 3950]
 [4050 4400 4750 5100 5450]
 [5150 5600 6050 6500 6950]]


LinAlgError: Singular matrix

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [15]:
tmp = np.zeros((8,8), dtype=int)
tmp[1::2,::2] = 1
tmp[::2,1::2] = 1
tmp

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])